### ISSUE TITLE
[Node] Error: Cannot find module 'rxjs/Subject'

### ISSUE THREAD

**Issue by aminebizid** [laskoviymishka/Unicorn.Cms#1]
[Node] Error: Cannot find module 'rxjs/Subject'
[Node]     at Function.Module._resolveFilename (module.js:339:15)
[Node]     at Function.Module._load (module.js:290:25)
[Node]     at Module.require (module.js:367:17)
[Node]     at require (internal/module.js:16:19)
[Node]     at Object.<anonymous> (C:\labo\Unicorn.Cms\src\Unicorn.Cms\node_modules\@angular\core\src\facade\async.js:11:17)
[Node]     at Module._compile (module.js:413:34)
[Node]     at Object.Module._extensions..js (module.js:422:10)
[Node]     at Module.load (module.js:357:32)
[Node]     at Function.Module._load (module.js:314:12)
[Node]     at Module.require (module.js:367:17)

**Comment by aminebizid** [comment]
it worked after :
 npm install rxjs@~5.0.0-beta.6 --save
npm install preboot --save

**Comment by laskoviymishka** [comment]
thnx! i'll fix it
